# This is a Docker Compose file for the InfluxData documentation site.
## Run documentation tests for code samples.
name: influxdata-docs
services:
  vale:
    image: jdkato/vale:latest
    container_name: docs-lint
    profiles:
      - lint
    volumes:
      - type: bind 
        source: ./tmp/lint
        target: /src
    working_dir: /src
    entrypoint: ["/bin/vale"]
    build:
      context: .
      dockerfile_inline: |
        COPY .ci /src/.ci
        COPY **/.vale.ini /src/
  test:
    container_name: docs-tests
    profiles:
      - test
    volumes:
      - type: bind
        source: ./test
        target: /test
        read_only: true
      - type: bind
        source: ./data 
        target: /appdata
        read_only: true 
      - type: bind
        source: ./tmp/test 
        target: /app/src
      - type: bind
        source: ./static/downloads
        target: /data
        read_only: true
    build:
      context: .
      dockerfile: test.Dockerfile
  ## Run InfluxData documentation with the hugo development server on port 1313.
  ## For more information about the hugomods/hugo image, see
  ## https://docker.hugomods.com/docs/development/docker-compose/
  local-dev:
    image: hugomods/hugo:exts-0.123.8
    command: hugo server --bind 0.0.0.0
    ports:
      - 1313:1313
    volumes:
      - type: bind
        source: "$PWD"
        target: /src
      - type: bind
        source: $HOME/hugo_cache
        target: /tmp/hugo_cache
